import { BrainCircuit, Network, GitGraph } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const models = [
  {
    id: "ctgan",
    name: "CTGAN",
    fullName: "Conditional Tabular GAN",
    description: "A deep learning model based on Generative Adversarial Networks (GANs) specifically designed for tabular data.",
    howItWorks: "Uses a generator to create synthetic rows and a discriminator to distinguish them from real data. It handles continuous and discrete columns effectively using mode-specific normalization.",
    bestFor: ["Complex distributions", "High-cardinality categorical data", "Preserving correlations"],
    icon: BrainCircuit
  },
  {
    id: "vae",
    name: "VAE",
    fullName: "Variational Autoencoder",
    description: "A probabilistic generative model that learns the underlying distribution of the input data in a latent space.",
    howItWorks: "Encodes input data into a lower-dimensional latent space and then decodes it back. New data is generated by sampling from this latent space.",
    bestFor: ["Faster training", "Simpler datasets", "Anomaly detection"],
    icon: Network
  },
  {
    id: "gaussian",
    name: "Gaussian Copula",
    fullName: "Gaussian Copula Synthesis",
    description: "A statistical model that uses copulas to model the dependency structure of the data.",
    howItWorks: "Transforms columns to a standard normal distribution, learns the correlations (covariance), and samples from a multivariate normal distribution before transforming back.",
    bestFor: ["Small datasets", "Linear correlations", "Quick baseline generation"],
    icon: GitGraph
  }
];

export default function ModelsSection() {
  return (
    <section id="models" className="py-24 bg-background">
      <div className="container mx-auto px-6">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl font-bold tracking-tight mb-4">
            Powered by Advanced AI Models
          </h2>
          <p className="text-lg text-muted-foreground">
            We use state-of-the-art algorithms to ensure your synthetic data is as good as the real thing.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {models.map((model) => (
            <Card key={model.id} className="border-2 hover:border-primary/50 transition-colors">
              <CardHeader>
                <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4 text-primary">
                  <model.icon className="w-6 h-6" />
                </div>
                <CardTitle className="text-2xl">{model.name}</CardTitle>
                <CardDescription className="text-base font-medium text-primary">
                  {model.fullName}
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <p className="text-muted-foreground">
                  {model.description}
                </p>
                
                <div className="bg-muted/50 p-4 rounded-lg text-sm">
                  <span className="font-semibold block mb-1">How it works:</span>
                  {model.howItWorks}
                </div>

                <div>
                  <span className="text-sm font-semibold text-muted-foreground block mb-2">Best for:</span>
                  <div className="flex flex-wrap gap-2">
                    {model.bestFor.map((tag) => (
                      <Badge key={tag} variant="secondary">
                        {tag}
                      </Badge>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}
